version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: change_me
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  api:
    build: .
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  db_data:
